---
namespace: dataslab
name: utils
version: 1.0.0
readme: README.md
authors:
  - Eugene M. <em@dataslab.eu>
description: Utils
license: GPL-3.0-or-later
min_ansible_version: "2.9"
platforms:
  - name: Linux
    versions:
      - all
galaxy_tags: []
dependencies: {}

tags: []
